### ISSUE TITLE
[Error-Handling] canvas가 가운데 정렬이 안되는 문제

### ISSUE THREAD

**Issue by shren207** [shren207/we-ar#15]
### 발생한 에러
`canvas` 요소가 화면 정 가운데에 배치가 안 되는 이슈가 있었다.
가로 정렬은 되는데 세로 정렬이 안 되어서 검색해서 문제를 해결하였다.

### 에러 핸들링 방법
```css
canvas {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: auto;
        background-color: white;
      }
```

![스크린샷 2022-04-20 오후 6 27 35](https://user-images.githubusercontent.com/85833148/164197241-0b3eb1aa-ce19-4b89-bcd1-fd24b594080a.png)
> position 값을 적용한 결과 canvas가 화면 정가운데로 배치되었다.

### 참고 링크
* [Centering a canvas](https://stackoverflow.com/questions/1152203/centering-a-canvas)
